apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipmentv11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipmentv11
  template:
    metadata:
      labels:
        app: shipmentv11
    spec:
      containers:
      - name: shipmentv11
        image: "shipment:v1.1"
        ports:
        - containerPort: 8080